export const FETCHDATA = 'FETCHDATA';
export const FETCHCOUNTER = 'FETCHCOUNTER';
export const ISTIMEFINISHED = 'ISTIMEFINISHED';
export const GETSCORE = 'GETSCORE';
export const CURRENTUSERDATA = 'CURRENTUSERDATA';
export const FETCHDATABYEMAIL = 'FETCHDATABYEMAIL';
export const ISLOADING = 'ISLOADING';